# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('display_order', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='info_groups',
            field=models.ManyToManyField(blank=True, null=True, to='legal.DocumentInfoGroup'),
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legal.DocumentInfoGroup'),
        ),
    ]
