# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_auto_20180921_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinfogroup',
            name='questions',
        ),
        migrations.AlterModelOptions(
            name='documentinfo',
            options={'ordering': ('display_order',)},
        ),
        migrations.RemoveField(
            model_name='document',
            name='info_groups',
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DocumentInfoGroup',
        ),
    ]
