# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='nav_menu',
            field=models.ForeignKey(blank=True, help_text=b'An Optional navigation menu to display on this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitetree.Tree'),
        ),
    ]
